# Generated by Django 5.2.1 on 2025-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="test", max_length=150),
            preserve_default=False,
        ),
    ]
