services:
  postgres:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - security_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_SECRET_KEY: "supersecretkey"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: security_db
      DB_USER: admin
      DB_PASS: secret
    depends_on:
      - postgres

volumes:
  security_pgdata: