# Generated by Django 5.2.1 on 2025-05-27 13:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileSystemNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_directory", models.BooleanField(default=False)),
                ("size_bytes", models.BigIntegerField(null=True)),
                ("mime_type", models.CharField(max_length=100, null=True)),
                ("is_public_root", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="files.filesystemnode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner"], name="files_files_owner_i_a97f7f_idx"),
                    models.Index(fields=["parent"], name="files_files_parent__8464a3_idx"),
                ],
                "unique_together": {("owner", "parent", "name", "deleted_at")},
            },
        ),
    ]
