# Generated by Django 5.2.1 on 2025-05-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_alter_filesystemnode_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesystemnode",
            name="is_public_root",
        ),
    ]
